class BikeGPSApp{
 constructor(){this.startBtn=q('startBtn');this.stopBtn=q('stopBtn');this.saveBtn=q('saveBtn');this.elapsedEl=q('elapsed-time');this.speedEl=q('current-speed');this.avgEl=q('avg-speed');this.maxEl=q('max-speed');this.distEl=q('current-distance');this.remEl=q('remaining-distance');this.latEl=q('latitude');this.lngEl=q('longitude');this.accEl=q('accuracy');this.statusEl=q('gps-status');this.targetEl=q('target-speed');this.isTracking=false;this.startTime=0;this.elapsedSeconds=0;this.totalDistance=0;this.last=null;this.speeds=[];this.maxSpeed=0;this.timer=null;this.bind();this.initMap();}
 bind(){this.startBtn.onclick=()=>this.start();this.stopBtn.onclick=()=>this.stop();this.saveBtn.onclick=()=>this.save();document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>this.switchTab(b.dataset.tab));this.targetEl.oninput=()=>this.updateStats()}
 initMap(){if(mapManager.initMap())this.status('준비 완료 · 시작 버튼을 누르면 GPS 추적을 시작합니다.')}
 start(){if(this.isTracking)return;this.isTracking=true;this.startTime=Date.now();this.elapsedSeconds=0;this.totalDistance=0;this.last=null;this.speeds=[];this.maxSpeed=0;mapManager.reset();gpsTracker.reset();this.startBtn.disabled=true;this.stopBtn.disabled=false;this.saveBtn.disabled=false;this.status('📍 GPS 위치 추적 중…');this.timer=setInterval(()=>{this.elapsedSeconds=Math.floor((Date.now()-this.startTime)/1000);this.updateStats()},500);gpsTracker.startTracking(c=>this.location(c),e=>{this.status('❌ '+e);this.stop()})}
 stop(){if(!this.isTracking)return;this.isTracking=false;gpsTracker.stopTracking();if(this.timer){clearInterval(this.timer);this.timer=null}this.startBtn.disabled=false;this.stopBtn.disabled=true;this.status('✅ 추적 완료');mapManager.fitBounds()}
 location(c){this.latEl.textContent=c.latitude.toFixed(6);this.lngEl.textContent=c.longitude.toFixed(6);this.accEl.textContent=Math.round(c.accuracy)+' m';if(this.last){const d=this.distance(this.last,c);if(d>=1&&d<100){this.totalDistance+=d/1000;const dt=gpsTracker.lastUpdateTime||1;let speed=c.speed!=null&&c.speed>=0?c.speed*3.6:(d/dt)*3.6;if(speed<80){this.speeds.push(speed);if(this.speeds.length>60)this.speeds.shift();this.maxSpeed=Math.max(this.maxSpeed,speed)}}}this.last=c;mapManager.updateCurrentMarker(c);bikeNav.updateLocation(c.latitude,c.longitude);this.updateStats()}
 updateStats(){const avg=this.elapsedSeconds>0?this.totalDistance/(this.elapsedSeconds/3600):0;const recent=this.speeds.length?this.speeds.slice(-5).reduce((a,b)=>a+b,0)/Math.min(5,this.speeds.length):0;this.elapsedEl.textContent=this.fmt(this.elapsedSeconds);this.speedEl.textContent=recent.toFixed(1);this.avgEl.textContent=avg.toFixed(1)+' km/h';this.maxEl.textContent=this.maxSpeed.toFixed(1)+' km/h';this.distEl.innerHTML=this.totalDistance.toFixed(2)+'<span>km</span>';const target=parseFloat(this.targetEl.value)||0;this.remEl.textContent=target>0&&avg>0?Math.max(0,target-this.totalDistance).toFixed(2)+' km':'-';if(target>0&&recent>=target)bikeNav.markTargetReached()}
 save(){const record={distanceKm:+this.totalDistance.toFixed(3),elapsedSeconds:this.elapsedSeconds,avgSpeedKmh:+(this.elapsedSeconds?this.totalDistance/(this.elapsedSeconds/3600):0).toFixed(2),maxSpeedKmh:+this.maxSpeed.toFixed(2),savedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bike-ride-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 switchTab(name){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-content').forEach(c=>c.classList.toggle('active',c.id===name+'-tab'));if(name==='map'){setTimeout(()=>{mapManager.initMap(bikeNav.currentLocation||mapManager.currentLocation||undefined);if(mapManager.map){mapManager.map.relayout();if(bikeNav.destination)bikeNav.showDestinationMarker()}},80)}}
 status(s){this.statusEl.textContent=s}distance(a,b){return bikeNav.haversine({lat:a.latitude,lng:a.longitude},{lat:b.latitude,lng:b.longitude})}fmt(s){return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}
}
function q(id){return document.getElementById(id)}
window.addEventListener('DOMContentLoaded',()=>window.bikeApp=new BikeGPSApp());
