const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const NAV_CONFIG={OFF_ROUTE_DISTANCE_M:40,OFF_ROUTE_CONSECUTIVE_FIXES:3,REROUTE_COOLDOWN_MS:20000,FOLLOW_OFFSET_PX:110,GPS_JUMP_MAX_M:200};
function createNavState(){return{watchId:null,startedAt:null,distance:0,lastPos:null,lastTimestamp:null,paused:false,pausedAt:null,pausedDuration:0,summary:null,steps:[],currentStep:0,progressDistance:0,follow:true,heading:0,currentSpeed:0,averageSpeed:0,maxSpeed:0,offRouteCount:0,lastRecalcAt:0,recalculating:false,hudMode:'eta'}}
const state={screen:'map',map:null,currentLocation:null,gpsMarker:null,gpsMarkerEl:null,gpsMarkerMode:null,searchMarkers:[],routes:[],routeLines:[],selectedRoute:0,selectedPlace:null,searchResults:[],searchQuery:'',departure:null,destination:null,editingEndpoint:null,searchSeq:0,searchController:null,routeSeq:0,nav:createNavState()};
const ui={mapHeader:$('#mapHeader'),quick:$('#quickActions'),search:$('#searchPanel'),routeEditor:$('#routeEditor'),sheet:$('#sheet'),sheetContent:$('#sheetContent'),routeCards:$('#routeCards'),start:$('#startNavBtn'),bottom:$('#bottomNav'),nav:$('#navOverlay'),controls:$('#mapControls')};
let toastTimer, searchTimer, sheetY=0, sheetDrag=null;

function toast(msg,ms=1800){clearTimeout(toastTimer);const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');toastTimer=setTimeout(()=>t.classList.add('hidden'),ms)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtKm(m){return `${(Math.max(0,m||0)/1000).toFixed(m>=10000?0:1)} km`}
function fmtMin(sec){return `${Math.max(1,Math.round((sec||0)/60))}분`}
function hav(a,b){if(!a||!b)return 0;const R=6371000,p=Math.PI/180,dLat=(b.latitude-a.latitude)*p,dLon=(b.longitude-a.longitude)*p,x=Math.sin(dLat/2)**2+Math.cos(a.latitude*p)*Math.cos(b.latitude*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function normalize(s){return String(s||'').replace(/\s+/g,'').toLowerCase()}
function isTransit(p){return /(지하철|철도|기차|역사|교통|수도권전철)/.test(p.category||'')}
function rankPlaces(list,q){const nq=normalize(q),station=/역$/.test(nq);return list.map((p,i)=>({p,i,score:(normalize(p.name)===nq?100000:0)+(station&&isTransit(p)?20000:0)+(normalize(p.name).startsWith(nq)?5000:0)+(normalize(p.name).includes(nq)?1000:0)})).sort((a,b)=>b.score-a.score||a.i-b.i||(a.p.distance??1e12)-(b.p.distance??1e12)).map(x=>x.p)}

async function loadKakao(){if(window.kakao?.maps)return;const cfg=await fetch('/api/config').then(r=>r.json());if(!cfg.kakaoJsKey)throw new Error(cfg.error||'Kakao JS key 없음');await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(cfg.kakaoJsKey)}&autoload=false`;s.onload=()=>kakao.maps.load(resolve);s.onerror=reject;document.head.appendChild(s)})}
async function initMap(){await loadKakao();const fallback=new kakao.maps.LatLng(37.5665,126.9780);state.map=new kakao.maps.Map($('#map'),{center:fallback,level:5});state.map.setDraggable(true);state.map.setZoomable(true);kakao.maps.event.addListener(state.map,'click',()=>{if(state.screen==='place')hideSheet()});kakao.maps.event.addListener(state.map,'dragstart',()=>{if(state.screen==='navigation')setNavigationFollow(false)});await locate(true).catch(()=>toast('현재 위치를 확인할 수 없습니다.'));renderScreen('map',false)}
function setGpsMarker(p,navigation=false,heading=0){if(!p||!state.map)return;const mode=navigation?'navigation':'map',ll=new kakao.maps.LatLng(p.latitude,p.longitude);if(!state.gpsMarker){state.gpsMarkerEl=document.createElement('div');state.gpsMarker=new kakao.maps.CustomOverlay({position:ll,content:state.gpsMarkerEl,zIndex:9,map:state.map})}if(state.gpsMarkerMode!==mode){state.gpsMarkerMode=mode;state.gpsMarkerEl.className=navigation?'gps-arrow':'gps-dot';state.gpsMarkerEl.textContent=navigation?'▲':'';state.gpsMarkerEl.style.cssText=navigation?'':'width:22px;height:22px;border-radius:50%;background:#1683ff;border:4px solid white;box-shadow:0 2px 8px #1683ff88'}if(navigation)state.gpsMarkerEl.style.transform=`rotate(${Number.isFinite(heading)?heading:0}deg)`;state.gpsMarker.setPosition(ll);state.gpsMarker.setMap(state.map)}
async function locate(center=false){const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:9000,maximumAge:5000}));const p={latitude:pos.coords.latitude,longitude:pos.coords.longitude,name:'현재 위치'};state.currentLocation=p;setGpsMarker(p,state.screen==='navigation',state.nav.heading);if(center){if(state.screen==='navigation'){setNavigationFollow(true);followNavigationPosition(p)}else state.map.panTo(new kakao.maps.LatLng(p.latitude,p.longitude))}return p}
function clearSearchMarkers(){state.searchMarkers.forEach(m=>m.setMap(null));state.searchMarkers=[]}
function clearRoutes(){state.routeLines.forEach(l=>l?.setMap(null));state.routeLines=[]}
function showMarkers(places){clearSearchMarkers();const bounds=new kakao.maps.LatLngBounds();places.forEach((p,i)=>{const ll=new kakao.maps.LatLng(p.latitude,p.longitude);const m=new kakao.maps.Marker({position:ll,map:state.map,zIndex:3});kakao.maps.event.addListener(m,'click',()=>openPlace(p));state.searchMarkers.push(m);bounds.extend(ll)});if(places.length)state.map.setBounds(bounds,60,40,Math.min(360,innerHeight*.42))}

function renderScreen(screen,push=true,data={}){state.screen=screen;document.body.classList.toggle('navigation-active',screen==='navigation');[ui.mapHeader,ui.quick,ui.search,ui.routeEditor,ui.sheet,ui.routeCards,ui.start,ui.bottom,ui.nav].forEach(x=>x.classList.add('hidden'));ui.controls.classList.remove('hidden');if(screen==='map'){ui.mapHeader.classList.remove('hidden');ui.quick.classList.remove('hidden');ui.bottom.classList.remove('hidden');setControlBottom(78)}else if(screen==='search'){ui.search.classList.remove('hidden');ui.controls.classList.add('hidden');setTimeout(()=>$('#searchInput').focus(),30)}else if(screen==='results'||screen==='place'){ui.mapHeader.classList.remove('hidden');ui.sheet.classList.remove('hidden');setSheet('mid')}else if(screen==='route'){ui.routeEditor.classList.remove('hidden');ui.routeCards.classList.remove('hidden');ui.start.classList.remove('hidden');setControlBottom(250)}else if(screen==='navigation'){ui.nav.classList.remove('hidden');ui.controls.classList.add('hidden');syncNavigationViewport()}if(screen!=='navigation'&&state.currentLocation)setGpsMarker(state.currentLocation,false);if(push)history.pushState({screen,...data},'',`#${screen}`);setTimeout(()=>state.map?.relayout(),50)}
function restoreScreen(screen){renderScreen(screen,false);if(screen!=='route'&&screen!=='navigation')clearRoutes();if(screen==='map')clearSearchMarkers();else if(screen==='results'){showMarkers(state.searchResults);renderResultsContent(state.searchResults,state.searchQuery)}else if(screen==='place'&&state.selectedPlace){const p=state.selectedPlace;state.map.panTo(new kakao.maps.LatLng(p.latitude,p.longitude));renderPlaceContent(p)}else if(screen==='route'&&state.routes.length){clearSearchMarkers();drawRoutes();renderRouteCards()}else if(screen==='navigation'&&state.routes[state.selectedRoute]){clearSearchMarkers();state.routeLines.forEach((l,i)=>{if(l)l.setMap(i===state.selectedRoute?state.map:null)});state.routeLines[state.selectedRoute]?.setOptions({strokeWeight:8,strokeColor:'#0878f9',strokeOpacity:.95,zIndex:8});if(state.nav.watchId==null)startWatch();updateNavHud(state.currentLocation)}}
function handlePopState(e){clearTimeout(searchTimer);cancelSearch();state.routeSeq++;if(state.screen==='navigation'&&state.nav.watchId!=null){navigator.geolocation.clearWatch(state.nav.watchId);state.nav.watchId=null}const entry=e.state||{},screen=entry.screen||'map';if(screen==='results'&&Array.isArray(entry.places)){state.searchResults=entry.places;state.searchQuery=entry.q||''}else if(screen==='place'&&entry.place)state.selectedPlace=entry.place;restoreScreen(screen)}
window.addEventListener('popstate',handlePopState);
function setControlBottom(px){ui.controls.style.setProperty('--control-bottom',`${px}px`)}
function setSheet(mode){const h=ui.sheet.offsetHeight||Math.min(innerHeight*.66,560),y=mode==='low'?h*.68:mode==='high'?h*.08:h*.38;sheetY=y;ui.sheet.style.setProperty('--sheet-y',`${y}px`);setControlBottom(Math.max(90,h-y+18))}
function hideSheet(){ui.sheet.classList.add('hidden');setControlBottom(90)}

function cancelSearch(){state.searchSeq++;state.searchController?.abort();state.searchController=null}
async function searchPlaces(q,signal){const p=new URLSearchParams({query:q,size:'15'});if(state.currentLocation){p.set('x',state.currentLocation.longitude);p.set('y',state.currentLocation.latitude)}const r=await fetch('/api/place-search?'+p,{signal});const d=await r.json();if(!r.ok)throw new Error(d.error||'검색 실패');return rankPlaces(d.results||[],q)}
async function doSearch(q,live=false){q=q.trim();if(!q)return;cancelSearch();const seq=state.searchSeq,controller=new AbortController();state.searchController=controller;try{const places=await searchPlaces(q,controller.signal);if(seq!==state.searchSeq)return;if(live){renderLive(places);return}renderResults(places,q)}catch(e){if(e.name!=='AbortError'&&seq===state.searchSeq)toast(e.message)}finally{if(seq===state.searchSeq)state.searchController=null}}
async function choosePlace(p,forceDestination=false){const target=forceDestination?'destination':state.editingEndpoint;if(target==='departure'){state.departure=p;state.editingEndpoint=null;if(state.destination)return loadRoutes();state.editingEndpoint='destination';return openSearch('destination')}if(target==='destination'){state.destination=p;state.editingEndpoint=null;if(!state.departure)state.departure=state.currentLocation||await locate(false).catch(()=>null);if(!state.departure)return toast('출발 위치가 필요합니다.');return loadRoutes()}openPlace(p)}
function renderLive(places){const box=$('#liveResults');box.classList.remove('hidden');$('#searchLanding').classList.add('hidden');box.innerHTML=places.map((p,i)=>`<div class="live-row"><button class="place-main" data-i="${i}"><b>${esc(p.name)}</b><small>${esc(p.category)}</small><small>${esc(p.address)}</small></button><button class="route-mini" data-route="${i}">길찾기</button></div>`).join('')||'<p>검색 결과가 없습니다.</p>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>choosePlace(places[+b.dataset.i]));box.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>choosePlace(places[+b.dataset.route],true))}
function renderResultsContent(places,q){ui.sheetContent.innerHTML=`<div class="result-list"><h3>${esc(q)} <small>${places.length}개</small></h3>${places.map((p,i)=>`<div class="result-item"><button class="result-info" data-i="${i}"><b>${esc(p.name)}</b><small>${esc(p.category)}</small><small>${esc(p.address)}${p.distance!=null?` · ${(p.distance/1000).toFixed(1)}km`:''}</small></button><button class="route-mini" data-route="${i}">길찾기</button></div>`).join('')||'<p>검색 결과가 없습니다.</p>'}</div>`;ui.sheetContent.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>choosePlace(places[+b.dataset.i]));ui.sheetContent.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>choosePlace(places[+b.dataset.route],true))}
function renderResults(places,q){state.searchResults=places;state.searchQuery=q;renderScreen('results',true,{places,q});showMarkers(places);renderResultsContent(places,q)}
function renderPlaceContent(p){ui.sheetContent.innerHTML=`<div class="detail"><h2>${esc(p.name)}</h2><p>${esc(p.category)}</p><p>${esc(p.address)}</p>${p.phone?`<p>${esc(p.phone)}</p>`:''}${p.distance!=null?`<p>${(p.distance/1000).toFixed(1)} km</p>`:''}<div class="detail-actions"><button id="setStart" class="outline-btn">출발</button><button id="setEnd" class="primary-btn">도착</button></div></div>`;setSheet('high');$('#setStart').onclick=()=>setDeparture(p);$('#setEnd').onclick=()=>setDestination(p)}
function openPlace(p){state.selectedPlace=p;renderScreen('place',true,{place:p});const ll=new kakao.maps.LatLng(p.latitude,p.longitude);state.map.panTo(ll);renderPlaceContent(p)}
function setDeparture(p){state.departure=p;state.destination=null;state.editingEndpoint='destination';openSearch('destination');toast('출발지를 설정했습니다. 도착지를 선택하세요.')}
async function setDestination(p){state.destination=p;if(!state.departure)state.departure=state.currentLocation||await locate(false).catch(()=>null);if(!state.departure){toast('출발 위치가 필요합니다.');return}await loadRoutes()}
function openSearch(endpoint=null){cancelSearch();state.editingEndpoint=endpoint;renderScreen('search');$('#searchInput').value='';$('#liveResults').classList.add('hidden');$('#searchLanding').classList.remove('hidden')}

function extractPoints(route){const out=[];const add=(lat,lng)=>{lat=+lat;lng=+lng;if(Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180)out.push({latitude:lat,longitude:lng})};const walkCoordinates=o=>{if(!Array.isArray(o))return;if(o.length===2&&o.every(v=>Number.isFinite(+v))){add(o[1],o[0]);return}if(o.length>=4&&o.every(Number.isFinite)){for(let i=0;i+1<o.length;i+=2)add(o[i+1],o[i]);return}o.forEach(walkCoordinates)};const walk=o=>{if(!o)return;if(Array.isArray(o)){if(o.length===2&&o.every(v=>Number.isFinite(+v))){const a=+o[0],b=+o[1];Math.abs(a)>90?add(b,a):add(a,b);return}if(o.length>=4&&o.every(Number.isFinite)){for(let i=0;i+1<o.length;i+=2){const a=+o[i],b=+o[i+1];if(Math.abs(a)>90)add(b,a);else add(a,b)}return}o.forEach(walk);return}if(typeof o!=='object')return;if(Array.isArray(o.vertexes))walk(o.vertexes);if(Array.isArray(o.points))o.points.forEach(p=>Array.isArray(p)?(Math.abs(+p[0])>90?add(p[1],p[0]):add(p[0],p[1])):add(p.y??p.latitude,p.x??p.longitude));if(Array.isArray(o.coordinates))walkCoordinates(o.coordinates);['sections','roads','features','legs','steps','path','geometry'].forEach(k=>{if(o[k])walk(o[k])})};walk(route);return out.filter((p,i,a)=>!i||p.latitude!==a[i-1].latitude||p.longitude!==a[i-1].longitude)}
async function fetchRoutes(a=state.departure,b=state.destination){const p=new URLSearchParams({start_x:a.longitude,start_y:a.latitude,end_x:b.longitude,end_y:b.latitude});const r=await fetch('/api/bicycle-route?'+p),d=await r.json();if(!r.ok)throw new Error(d.error||'경로 검색 실패');return d.routes||[]}
function prepareRoutes(routes){return routes.filter(r=>{r._points=extractPoints(r.route);r._steps=extractNavigationSteps(r.route);return r._points.length>1&&r.totalDistance>0})}
async function loadRoutes(){if(state.nav.watchId!=null){navigator.geolocation.clearWatch(state.nav.watchId);state.nav.watchId=null}state.routeSeq++;const routeSeq=state.routeSeq;clearRoutes();state.routes=[];state.selectedRoute=null;ui.start.classList.add('hidden');renderScreen('route');updateRouteFields();ui.routeCards.innerHTML='<div class="route-card">경로를 찾는 중...</div>';clearSearchMarkers();try{const fetched=await fetchRoutes();if(routeSeq!==state.routeSeq)return;state.routes=prepareRoutes(fetched);if(!state.routes.length)throw new Error('표시 가능한 자전거 경로가 없습니다.');state.selectedRoute=0;drawRoutes();renderRouteCards();ui.start.classList.remove('hidden')}catch(e){if(routeSeq!==state.routeSeq)return;clearRoutes();state.routes=[];state.selectedRoute=null;ui.start.classList.add('hidden');ui.routeCards.innerHTML=`<div class="route-card">${esc(e.message)}</div>`;toast(e.message)}}
function updateRouteFields(){$('#departureField b').textContent=state.departure?.name||'현재 위치';$('#destinationField b').textContent=state.destination?.name||'목적지'}
function drawRoutes(){clearRoutes();const bounds=new kakao.maps.LatLngBounds();state.routes.forEach((r,i)=>{const pts=r._points||extractPoints(r.route);r._points=pts;const path=pts.map(p=>{const ll=new kakao.maps.LatLng(p.latitude,p.longitude);bounds.extend(ll);return ll});if(path.length>1){const line=new kakao.maps.Polyline({map:state.map,path,strokeWeight:i===state.selectedRoute?8:5,strokeColor:i===state.selectedRoute?'#0878f9':'#98a7b8',strokeOpacity:i===state.selectedRoute?.95:.62,strokeStyle:'solid',zIndex:i===state.selectedRoute?8:3});state.routeLines.push(line)}else state.routeLines.push(null)});if(!bounds.isEmpty())state.map.setBounds(bounds,70,150,300)}
function selectRoute(i){state.selectedRoute=i;state.routeLines.forEach((l,j)=>{if(!l)return;l.setOptions({strokeWeight:j===i?8:5,strokeColor:j===i?'#0878f9':'#98a7b8',strokeOpacity:j===i?.95:.62,zIndex:j===i?8:3})});renderRouteCards()}
function renderRouteCards(){ui.routeCards.innerHTML=state.routes.map((r,i)=>`<button class="route-card ${i===state.selectedRoute?'active':''}" data-i="${i}"><b>${esc(r.label||`경로 ${i+1}`)}</b><strong>${fmtMin(r.totalTime)}</strong><small>${fmtKm(r.totalDistance)}</small></button>`).join('');ui.routeCards.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>selectRoute(+b.dataset.i))}

function bearing(a,b){const p=Math.PI/180,y=Math.sin((b.longitude-a.longitude)*p)*Math.cos(b.latitude*p),x=Math.cos(a.latitude*p)*Math.sin(b.latitude*p)-Math.sin(a.latitude*p)*Math.cos(b.latitude*p)*Math.cos((b.longitude-a.longitude)*p);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function projectOnRoute(points,p){if(!points?.length||!p)return{progress:0,alongDistance:0,totalDistance:0,offRouteDistance:Infinity,heading:0};let total=0,bestAlong=0,bestDistance=Infinity,bestHeading=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],seg=hav(a,b),latScale=Math.cos(((a.latitude+b.latitude+p.latitude)/3)*Math.PI/180),vx=(b.longitude-a.longitude)*latScale,vy=b.latitude-a.latitude,wx=(p.longitude-a.longitude)*latScale,wy=p.latitude-a.latitude,den=vx*vx+vy*vy,t=den?Math.max(0,Math.min(1,(wx*vx+wy*vy)/den)):0,projected={latitude:a.latitude+(b.latitude-a.latitude)*t,longitude:a.longitude+(b.longitude-a.longitude)*t},distance=hav(p,projected);if(distance<bestDistance){bestDistance=distance;bestAlong=total+seg*t;bestHeading=bearing(a,b)}total+=seg}return{progress:total?bestAlong/total:0,alongDistance:bestAlong,totalDistance:total,offRouteDistance:bestDistance,heading:bestHeading}}
function extractNavigationSteps(route){const steps=[];for(const leg of route?.legs||[])for(const step of leg.steps||[]){const properties=step.properties||step,points=extractPoints(step.path||step),point=Number.isFinite(+properties.y)&&Number.isFinite(+properties.x)?{latitude:+properties.y,longitude:+properties.x}:points[0]||null;steps.push({guidance:String(properties.guidance||step.guidance||''),distance:+(properties.distance??step.distance??0)||0,time:+(properties.time??step.time??0)||0,point,points})}let along=0;for(const step of steps){step._startAlong=along;const geometryDistance=step.points.reduce((sum,p,i)=>sum+(i?hav(step.points[i-1],p):0),0);along+=geometryDistance||step.distance;step._endAlong=along}return steps}
function navigationInstruction(steps,index){const step=steps?.[index];if(!step)return'경로를 따라 이동';const guidance=step.guidance.trim();if(/좌회전|우회전|유턴|직진|회전|진입|도착/.test(guidance))return guidance;const next=steps[index+1],a=step.points?.at(-2),b=step.points?.at(-1),c=next?.points?.[1]||next?.points?.[0];if(a&&b&&c){let delta=((bearing(b,c)-bearing(a,b)+540)%360)-180;if(Math.abs(delta)>150)return'유턴';if(delta<-25)return'좌회전';if(delta>25)return'우회전'}return guidance||'직진'}
function resolveSpeed(coords,distance,elapsedMs){if(Number.isFinite(coords?.speed)&&coords.speed>=0)return coords.speed;return elapsedMs>0&&distance>=0?distance/(elapsedMs/1000):0}
function activeRideDuration(now=Date.now()){if(!state.nav.startedAt)return 0;return Math.max(0,now-state.nav.startedAt-state.nav.pausedDuration-(state.nav.pausedAt?now-state.nav.pausedAt:0))}
function setNavigationFollow(enabled){state.nav.follow=enabled;$('#navLocateBtn')?.classList.toggle('active',enabled)}
function followNavigationPosition(p){if(!state.map||!p||!state.nav.follow)return;state.map.setCenter(new kakao.maps.LatLng(p.latitude,p.longitude));state.map.panBy(0,-NAV_CONFIG.FOLLOW_OFFSET_PX)}
function syncNavigationViewport(){const height=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--nav-height',`${height}px`);if(state.screen==='navigation')setTimeout(()=>state.map?.relayout(),0)}
function drawNavigationRoute(){clearRoutes();const r=state.routes[state.selectedRoute];if(!r)return;const path=r._points.map(p=>new kakao.maps.LatLng(p.latitude,p.longitude));state.routeLines=Array(state.routes.length).fill(null);state.routeLines[state.selectedRoute]=new kakao.maps.Polyline({map:state.map,path,strokeWeight:8,strokeColor:'#0878f9',strokeOpacity:.95,strokeStyle:'solid',zIndex:8})}
function startNavigation(){const r=state.routes[state.selectedRoute];if(!r)return;const nav=createNavState();nav.startedAt=Date.now();nav.steps=r._steps||extractNavigationSteps(r.route);state.nav=nav;renderScreen('navigation');clearSearchMarkers();state.routeLines.forEach((l,i)=>{if(l)l.setMap(i===state.selectedRoute?state.map:null)});if(state.routeLines[state.selectedRoute])state.routeLines[state.selectedRoute].setOptions({strokeWeight:8,strokeColor:'#0878f9',strokeOpacity:.95,zIndex:8});setNavigationFollow(true);setGpsMarker(state.currentLocation,true,0);startWatch();updateNavHud(state.currentLocation);toast('안내를 시작합니다.')}
function startWatch(){if(state.nav.watchId!=null)navigator.geolocation.clearWatch(state.nav.watchId);state.nav.watchId=navigator.geolocation.watchPosition(pos=>{const now=pos.timestamp||Date.now(),p={latitude:pos.coords.latitude,longitude:pos.coords.longitude,name:'현재 위치'},d=state.nav.lastPos?hav(state.nav.lastPos,p):0,elapsed=state.nav.lastTimestamp?now-state.nav.lastTimestamp:0;let speed=resolveSpeed(pos.coords,d,elapsed);if(state.nav.paused)speed=0;else if(state.nav.lastPos&&d<NAV_CONFIG.GPS_JUMP_MAX_M)state.nav.distance+=d;if(Number.isFinite(pos.coords.heading)&&pos.coords.heading>=0)state.nav.heading=pos.coords.heading;else if(state.nav.lastPos&&d>2)state.nav.heading=bearing(state.nav.lastPos,p);state.nav.currentSpeed=Math.max(0,speed);state.nav.maxSpeed=Math.max(state.nav.maxSpeed,state.nav.currentSpeed);const duration=activeRideDuration(now);state.nav.averageSpeed=duration>0?state.nav.distance/(duration/1000):0;state.nav.lastPos=p;state.nav.lastTimestamp=now;state.currentLocation=p;setGpsMarker(p,true,state.nav.heading);if(!state.nav.paused)followNavigationPosition(p);updateNavHud(p,pos.coords.accuracy)},()=>toast('GPS 신호를 확인해주세요.'),{enableHighAccuracy:true,maximumAge:1000,timeout:10000})}
function formatM(m){return m<1000?`${Math.max(10,Math.round(m/10)*10)}m`:`${(m/1000).toFixed(1)}km`}
function turnSymbol(text){return/좌회전/.test(text)?'↰':/우회전/.test(text)?'↱':/유턴/.test(text)?'↶':/도착/.test(text)?'●':'↑'}
function updateNavHud(p,accuracy=0){const r=state.routes[state.selectedRoute];if(!r||!p)return;const projection=projectOnRoute(r._points,p);if(projection.offRouteDistance<=Math.max(NAV_CONFIG.OFF_ROUTE_DISTANCE_M,accuracy*1.5))state.nav.progressDistance=Math.max(state.nav.progressDistance,projection.alongDistance);const progress=projection.totalDistance?Math.min(1,state.nav.progressDistance/projection.totalDistance):0,remainD=Math.max(0,(r.totalDistance||0)*(1-progress)),remainS=Math.max(0,(r.totalTime||0)*(1-progress));let stepIndex=state.nav.steps.findIndex(step=>step._endAlong>=state.nav.progressDistance);if(stepIndex<0)stepIndex=Math.max(0,state.nav.steps.length-1);state.nav.currentStep=stepIndex;const instruction=navigationInstruction(state.nav.steps,stepIndex),next=navigationInstruction(state.nav.steps,stepIndex+1),stepDistance=Math.max(0,(state.nav.steps[stepIndex]?._endAlong||state.nav.progressDistance)-state.nav.progressDistance);$('#turnIcon').textContent=turnSymbol(instruction);$('#turnDistance').textContent=remainD<35?'곧 도착':`${formatM(stepDistance)} 후 ${instruction}`;$('#turnText').textContent=state.nav.paused?'안내 일시정지':instruction;$('#nextTurnText').textContent=next&&stepIndex+1<state.nav.steps.length?`다음 안내 · ${next}`:'목적지까지 경로 안내';$('#remainDistance').textContent=fmtKm(remainD);$('#speedText').textContent=`${Math.round(state.nav.currentSpeed*3.6)} km/h`;$('#navPrimaryLabel').textContent=state.nav.hudMode==='eta'?'도착 예정':'남은 시간';$('#navPrimaryValue').textContent=state.nav.hudMode==='eta'?new Date(Date.now()+remainS*1000).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}):fmtMin(remainS);const threshold=Math.max(NAV_CONFIG.OFF_ROUTE_DISTANCE_M,accuracy*1.5);state.nav.offRouteCount=projection.offRouteDistance>threshold?state.nav.offRouteCount+1:0;if(state.nav.offRouteCount>=NAV_CONFIG.OFF_ROUTE_CONSECUTIVE_FIXES)recalculateNavigationRoute('off-route');if(remainD<35&&state.nav.startedAt)finishNavigation(true)}
async function recalculateNavigationRoute(reason='manual'){const now=Date.now(),nav=state.nav;if(nav.recalculating||!state.currentLocation||!state.destination)return;if(reason==='off-route'&&now-nav.lastRecalcAt<NAV_CONFIG.REROUTE_COOLDOWN_MS)return;nav.recalculating=true;nav.lastRecalcAt=now;$('#navRouteStatus').textContent='경로 재탐색 중…';try{const previousMode=state.routes[state.selectedRoute]?.routeMode,routes=prepareRoutes(await fetchRoutes(state.currentLocation,state.destination));if(state.nav!==nav||state.screen!=='navigation')return;if(!routes.length)throw new Error('재탐색 가능한 경로가 없습니다.');let selected=routes.findIndex(r=>r.routeMode===previousMode);if(selected<0)selected=0;state.routes=routes;state.selectedRoute=selected;nav.steps=routes[selected]._steps;nav.currentStep=0;nav.progressDistance=0;nav.offRouteCount=0;drawNavigationRoute();updateNavHud(state.currentLocation);$('#navRouteStatus').textContent='새 경로 적용 완료';setTimeout(()=>{if(state.nav===nav)$('#navRouteStatus').textContent=''},1800)}catch(e){if(state.nav!==nav)return;nav.offRouteCount=0;$('#navRouteStatus').textContent='재탐색 실패';toast(e.message)}finally{if(state.nav===nav)nav.recalculating=false}}
function finishNavigation(arrived=false){if(state.nav.watchId!=null){navigator.geolocation.clearWatch(state.nav.watchId);state.nav.watchId=null}const duration=activeRideDuration();state.nav.averageSpeed=duration>0?state.nav.distance/(duration/1000):0;$('#summaryDistance').textContent=fmtKm(state.nav.distance);$('#summaryDuration').textContent=`${Math.max(1,Math.round(duration/60000))}분`;$('#summaryAverageSpeed').textContent=`${(state.nav.averageSpeed*3.6).toFixed(1)} km/h`;$('#summaryMaxSpeed').textContent=`${(state.nav.maxSpeed*3.6).toFixed(1)} km/h`;state.nav.summary={distance:state.nav.distance,duration,averageSpeed:state.nav.averageSpeed,maxSpeed:state.nav.maxSpeed,departure:state.departure,destination:state.destination,routeMode:state.routes[state.selectedRoute]?.routeMode,arrived,endedAt:new Date().toISOString()};$('#navMenu').classList.add('hidden');$('#saveModal').classList.remove('hidden')}
function resetAfterRide(){if(state.nav.watchId!=null)navigator.geolocation.clearWatch(state.nav.watchId);clearRoutes();state.routes=[];state.selectedRoute=null;state.departure=null;state.destination=null;state.selectedPlace=null;state.editingEndpoint=null;state.nav=createNavState();$('#saveModal').classList.add('hidden');renderScreen('map');locate(true).catch(()=>{})}
function saveRide(){try{let rides=[];try{rides=JSON.parse(localStorage.getItem('ridemate_rides')||'[]');if(!Array.isArray(rides))rides=[]}catch{rides=[]}rides.unshift(state.nav.summary);localStorage.setItem('ridemate_rides',JSON.stringify(rides.slice(0,100)));toast('주행 기록을 저장했습니다.');resetAfterRide()}catch{toast('저장하지 못했습니다. 저장공간을 확인해주세요.',3000)}}

$('#searchEntry').onclick=()=>openSearch();
$('#searchBack').onclick=()=>{cancelSearch();history.back()};
$('#routeBack').onclick=()=>history.back();
$('#searchClear').onclick=()=>{cancelSearch();$('#searchInput').value='';$('#liveResults').classList.add('hidden');$('#searchLanding').classList.remove('hidden');$('#searchInput').focus()};
$('#searchInput').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();cancelSearch();if(!q){$('#liveResults').classList.add('hidden');$('#searchLanding').classList.remove('hidden');return}searchTimer=setTimeout(()=>doSearch(q,true),280)});
$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(searchTimer);doSearch(e.target.value,false)}});
$('#bikeShopBtn').onclick=()=>{$('#searchInput').value='자전거샵';doSearch('자전거샵',true)};
$$('.recent').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;doSearch(b.dataset.query,false)});
$$('[data-quick]').forEach(b=>b.onclick=()=>toast(`${b.textContent.trim()} 주소를 먼저 등록해주세요.`));
$('#zoomIn').onclick=()=>state.map?.setLevel(Math.max(1,state.map.getLevel()-1));
$('#zoomOut').onclick=()=>state.map?.setLevel(Math.min(14,state.map.getLevel()+1));
$('#locateBtn').onclick=()=>locate(true).catch(()=>toast('현재 위치를 확인할 수 없습니다.'));
$('#compassBtn').onclick=()=>{state.map?.setLevel(state.map.getLevel());toast('북쪽 기준 지도')};
$('#departureField').onclick=()=>openSearch('departure');
$('#destinationField').onclick=()=>openSearch('destination');
$('#swapBtn').onclick=async()=>{if(!state.departure||!state.destination)return;[state.departure,state.destination]=[state.destination,state.departure];updateRouteFields();await loadRoutes()};
$('#startNavBtn').onclick=startNavigation;
$('#navMenuBtn').onclick=()=>$('#navMenu').classList.remove('hidden');
$('#closeNavMenu').onclick=()=>$('#navMenu').classList.add('hidden');
$('#endNavBtn').onclick=()=>finishNavigation(false);
$('#saveRideBtn').onclick=saveRide;
$('#discardRideBtn').onclick=resetAfterRide;
$('#navSearchBtn').onclick=()=>toast('주행 중 검색은 경유지 메뉴에서 사용합니다.');
$('#navLocateBtn').onclick=()=>{setNavigationFollow(true);if(state.currentLocation)followNavigationPosition(state.currentLocation)};
$('#navRecalcBtn').onclick=()=>recalculateNavigationRoute('manual');
$('#navInfoToggle').onclick=()=>{state.nav.hudMode=state.nav.hudMode==='eta'?'remaining':'eta';updateNavHud(state.currentLocation)};
$$('[data-nav-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.navAction;if(a==='pause'){const now=Date.now();state.nav.paused=!state.nav.paused;if(state.nav.paused)state.nav.pausedAt=now;else{state.nav.pausedDuration+=state.nav.pausedAt?now-state.nav.pausedAt:0;state.nav.pausedAt=null}b.querySelector('span').textContent=state.nav.paused?'계속':'일시정지';updateNavHud(state.currentLocation);toast(state.nav.paused?'안내를 일시정지했습니다.':'안내를 계속합니다.')}else if(a==='north'){toast('북쪽 기준으로 표시합니다.')}else if(a==='recalc'){$('#navMenu').classList.add('hidden');await recalculateNavigationRoute('manual')}else if(a==='waypoint'){toast('경유지 선택은 다음 검색에서 추가할 수 있습니다.')}else toast('설정을 변경했습니다.')});

$('#sheetHandle').addEventListener('pointerdown',e=>{sheetDrag={start:e.clientY,y:sheetY};ui.sheet.classList.add('dragging');$('#sheetHandle').setPointerCapture(e.pointerId)});
$('#sheetHandle').addEventListener('pointermove',e=>{if(!sheetDrag)return;const h=ui.sheet.offsetHeight;sheetY=Math.max(h*.05,Math.min(h*.75,sheetDrag.y+e.clientY-sheetDrag.start));ui.sheet.style.setProperty('--sheet-y',`${sheetY}px`);setControlBottom(Math.max(90,h-sheetY+18))});
const finishSheetDrag=()=>{if(!sheetDrag)return;const h=ui.sheet.offsetHeight,ratio=sheetY/h;sheetDrag=null;ui.sheet.classList.remove('dragging');setSheet(ratio<.25?'high':ratio>.58?'low':'mid')};$('#sheetHandle').addEventListener('pointerup',finishSheetDrag);$('#sheetHandle').addEventListener('pointercancel',finishSheetDrag);$('#sheetHandle').addEventListener('lostpointercapture',finishSheetDrag);

document.addEventListener('click',e=>{const row=e.target.closest('.live-row,.result-item');if(!row)return});
window.addEventListener('resize',()=>{state.map?.relayout();if(state.screen==='navigation')syncNavigationViewport();else if(!ui.sheet.classList.contains('hidden'))setSheet('mid')});
window.visualViewport?.addEventListener('resize',syncNavigationViewport);
(async()=>{try{await initMap()}catch(e){toast('지도를 불러오지 못했습니다: '+e.message,5000)}})();
