
const searchInput=document.getElementById("searchInput"),clearBtn=document.getElementById("clearBtn"),recentList=document.getElementById("recentList"),recentSection=document.getElementById("recentSection"),resultsSection=document.getElementById("resultsSection"),resultsList=document.getElementById("resultsList"),clearRecentBtn=document.getElementById("clearRecentBtn"),bikeShopBtn=document.getElementById("bikeShopBtn");
let recentSearches=[{name:"한강공원",address:"서울특별시 영등포구 여의동로"},{name:"잠실한강공원",address:"서울특별시 송파구 올림픽로"},{name:"북한강 자전거길",address:"경기도 남양주시"}];
function go(q){location.href="/result/?q="+encodeURIComponent(q)}
function renderRecent(){recentList.innerHTML="";recentSearches.forEach((item,index)=>{const row=document.createElement("div");row.className="recent-item";row.innerHTML=`<div class="recent-icon">⌖</div><div class="recent-info"><div class="recent-name">${item.name}</div><div class="recent-address">${item.address}</div></div><button class="recent-delete">×</button>`;row.querySelector(".recent-delete").onclick=()=>{recentSearches.splice(index,1);renderRecent()};row.querySelector(".recent-info").onclick=()=>go(item.name);recentList.appendChild(row)})}
async function showResults(q){q=q.trim();if(!q){resultsSection.classList.add("hidden");recentSection.classList.remove("hidden");return}recentSection.classList.add("hidden");resultsSection.classList.remove("hidden");resultsList.innerHTML='<div class="result-item"><div class="result-info"><div class="result-name">검색 중...</div></div></div>';try{let origin=RideMate.state.currentLocation;const items=await RideMate.search(q,origin);if(!items.length){resultsList.innerHTML='<div class="result-item"><div class="result-info"><div class="result-name">검색 결과가 없습니다.</div></div></div>';return}resultsList.innerHTML=items.slice(0,8).map((x,i)=>`<div class="result-item" data-i="${i}"><div class="result-icon">⌖</div><div class="result-info"><div class="result-name">${x.name}</div><div class="result-address">${x.address||x.category||""}</div></div><div class="result-distance">${x.distance!=null?(x.distance>=1000?(x.distance/1000).toFixed(1)+"km":x.distance+"m"):""}</div></div>`).join("");resultsList.querySelectorAll("[data-i]").forEach(el=>el.onclick=()=>go(q))}catch(e){resultsList.innerHTML=`<div class="result-item"><div class="result-info"><div class="result-name">${e.message}</div></div></div>`}}
let timer;searchInput.addEventListener("input",()=>{clearBtn.style.display=searchInput.value?"grid":"none";clearTimeout(timer);timer=setTimeout(()=>showResults(searchInput.value),250)});searchInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&searchInput.value.trim()){e.preventDefault();go(searchInput.value.trim())}});
clearBtn.onclick=()=>{searchInput.value="";clearBtn.style.display="none";resultsSection.classList.add("hidden");recentSection.classList.remove("hidden");searchInput.focus()};clearRecentBtn.onclick=()=>{recentSearches=[];renderRecent()};bikeShopBtn.onclick=()=>go("자전거샵");
document.querySelectorAll(".quick-actions button").forEach(b=>b.onclick=()=>alert(`${b.innerText.trim()} 주소 등록 기능과 연결 예정입니다.`));renderRecent();
